// <auto-generated />
namespace MVCWebApiTutorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedmethodtoorders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmethodtoorders));
        
        string IMigrationMetadata.Id
        {
            get { return "201806212022109_added method to orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
